### ISSUE TITLE
为什么我点击打开出现错误呢？就是点击图片出现404

### ISSUE THREAD

**Issue by Tiersy** [yalay/themes-tutucms#1]
为什么我点击打开出现错误呢？就是点击图片出现404 如图
可以留下一个联系方式吗？
![qq 20170719205126](https://user-images.githubusercontent.com/30291976/28367593-176d46b6-6cc4-11e7-927a-c83ff3223e46.jpg)

**Comment by yalay** [comment]
@Tiersy 不好意思 最近比较忙。搞定了不，你的实际文章页链接是啥，这个问题看起来和模版无关，可能是不支持伪静态之类的。

**Comment by Tiersy** [comment]
不行。还是错误，无法打开，昨天弄了好久还是一样。别人说是你模版缺少CSS 我也不知道什么问题，这是我网站`www.ee**cc.** `

**Comment by Tiersy** [comment]
我QQ  `577288***`  研究好久都不行，都准备放弃了

**Comment by yalay** [comment]
@Tiersy 晚上给你说啊

**Comment by yalay** [comment]
问题已解决，主要是模版是按照文章模式设计的，栏目不能设置为图集模式，修改为文章模式就可以了。
